### ISSUE TITLE
Catch 503s and consider them failures

### ISSUE THREAD

**Issue by jgrevich** [18F/identity-loadtest#38]
```
[2021-07-08 11:23:54,598] j13/ERROR/locust.user.task: 503 Server Error: Service Unavailable for url: https://sp-oidc-sinatra.pt.identitysandbox.gov/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 327, in execute_task
    task(self)
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/sp_sign_in.locustfile.py", line 9, in sp_sign_in_load_test
    flow_sp_sign_in.do_sign_in(self)
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/common_flows/flow_sp_sign_in.py", line 41, in do_sign_in
    resp = do_request(
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/common_flows/flow_helper.py", line 28, in do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/locust/clients.py", line 20, in raise_for_status
    Response.raise_for_status(self)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://sp-oidc-sinatra.pt.identitysandbox.gov/
```

**Comment by jgrevich** [comment]
This can be folded into #24
