### ISSUE TITLE
OIDC SP throws 500s under high load

### ISSUE THREAD

**Issue by jgrevich** [18F/identity-loadtest#40]
I noticed a number of 500 errors after fixing the 503s by upping the `passenger_max_pool_size` and `passenger_min_instances` to 512 (related to https://github.com/18F/identity-loadtest/issues/38)

```
[2021-07-08 11:50:02,398] j13/ERROR/locust.user.task: 500 Server Error: Internal Server Error for url: https://sp-oidc-sinatra.pt.identitysandbox.gov/auth/result?code=fca90bb7-a03d-46f2-9e7d-af1c44d85b6c&state=6b96a4be96869a5d5c40f7d7abd3077c
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.9/site-packages/locust/user/task.py", line 327, in execute_task
    task(self)
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/sp_sign_in.locustfile.py", line 9, in sp_sign_in_load_test
    flow_sp_sign_in.do_sign_in(self)
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/common_flows/flow_sp_sign_in.py", line 118, in do_sign_in
    resp = do_request(
  File "/Users/jjg/Documents/sources/login/identity-loadtest/load_testing/common_flows/flow_helper.py", line 28, in do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/locust/clients.py", line 20, in raise_for_status
    Response.raise_for_status(self)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://sp-oidc-sinatra.pt.identitysandbox.gov/auth/result?code=fca90bb7-a03d-46f2-9e7d-af1c44d85b6c&state=6b96a4be96869a5d5c40f7d7abd3077c
```

~I can't seem to find anything more about them in the ngnix error log and there doesn't seem to be a dedicated log for the sinatra app. Events like this should be logged somewhere so we can determine why the app is failing.~

`passenger.log`
```
App 1838 output: 2021-07-13 21:01:25 - JWT::DecodeError - Nil JSON web token:
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/jwt-2.1.0/lib/jwt.rb:26:in `decode'
App 1838 output: 	/srv/sp-oidc-sinatra/releases/20210713171359/app.rb:209:in `userinfo'
App 1838 output: 	/srv/sp-oidc-sinatra/releases/20210713171359/app.rb:80:in `block in <class:OpenidConnectRelyingParty>'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
App 1838 output: 	/srv/sp-oidc-sinatra/shared/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
App 1838 output: 	/opt/ruby_build/versions/2.6.7/lib/ruby/gems/2.6.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 1838 output: 	/opt/ruby_build/versions/2.6.7/lib/ruby/gems/2.6.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 1838 output: 	/opt/ruby_build/versions/2.6.7/lib/ruby/gems/2.6.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 1838 output: 	/opt/ruby_build/versions/2.6.7/lib/ruby/gems/2.6.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 1838 output: 	/opt/ruby_build/versions/2.6.7/lib/ruby/gems/2.6.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

Any idea why at high load we're seeing this issue (`Nil JSON web token`)?

**Comment by jgrevich** [comment]
Oddly that's the same error we got when we had the wrong key configured. I wonder if it's a disk IO issue. I'm closing this since we have a new stack and this is over a year old.
